# Generated by Django 6.0.3 on 2026-04-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs2_match_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
